#!/usr/bin/env bash

configuration_catalog_ids() {
  awk -F '\t' '!/^#/ && NF >= 6 {print $1}' "$ROOT_DIR/configurations/catalog.tsv"
}

configuration_field() {
  local id="$1" column="$2"
  awk -F '\t' -v id="$id" -v column="$column" '$1 == id {print $column; exit}' "$ROOT_DIR/configurations/catalog.tsv"
}

configuration_requirement_available() {
  case "$1" in
    github-cli) command -v gh >/dev/null 2>&1 ;;
    spotify-player) command -v spotify_player >/dev/null 2>&1 || command -v spotify-player >/dev/null 2>&1 ;;
    *) command -v "$1" >/dev/null 2>&1 ;;
  esac
}

available_configuration_ids() {
  local id requirements requirement available
  local -a required_items=()
  while IFS=$'\t' read -r id _ requirements _; do
    [[ -n "$id" && "$id" != \#* ]] || continue
    available=true
    IFS=',' read -ra required_items <<<"$requirements"
    for requirement in "${required_items[@]}"; do
      configuration_requirement_available "$requirement" || available=false
    done
    [[ "$available" == true ]] && printf '%s\n' "$id"
  done < "$ROOT_DIR/configurations/catalog.tsv"
}

validate_configuration_selection() {
  local id preset_count=0
  for id in "$@"; do [[ "$id" == starship-preset-* ]] && ((preset_count += 1)); done
  ((preset_count <= 1)) || die "Choose only one Starship preset."
}

configuration_label() {
  local label
  label="$(awk -F '\t' -v id="$1" '$1 == id {print $2; exit}' "$ROOT_DIR/configurations/catalog.tsv")"
  printf '%s\n' "${label:-$1}"
}

configuration_is_complete() {
  local id="$1" fish_path current_shell config account_name="${USER:-$(id -un)}"
  case "$id" in
    fish-login-shell)
      fish_path="$(command -v fish 2>/dev/null || true)"
      [[ -n "$fish_path" ]] || return 1
      current_shell="$(getent passwd "$account_name" 2>/dev/null | awk -F: '{print $7}')"
      [[ "${current_shell:-${SHELL:-}}" == "$fish_path" ]]
      ;;
    fish-starship)
      config="${XDG_CONFIG_HOME:-$HOME/.config}/fish/config.fish"
      grep -Fq '# >>> linux-bootstrap starship >>>' "$config" 2>/dev/null
      ;;
    micro-developer-essentials)
      config="${MICRO_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/micro}"
      local plugin
      [[ -s "$config/.linux-bootstrap-developer-essentials-v1" ]] || return 1
      for plugin in lsp fzf filemanager snippets autofmt detectindent jump palettero quickfix editorconfig runit; do
        [[ -s "$config/plug/$plugin/repo.json" ]] || return 1
      done
      ;;
    starship-preset-*)
      config="${XDG_CONFIG_HOME:-$HOME/.config}/starship.toml"
      grep -Fq "# Generated by linux-bootstrap: ${id#starship-preset-}" "$config" 2>/dev/null
      ;;
    upstream-github-auth)
      command -v gh >/dev/null 2>&1 && gh auth status --hostname github.com >/dev/null 2>&1
      ;;
    upstream-spotify-auth)
      [[ -s "${XDG_CACHE_HOME:-$HOME/.cache}/spotify-player/user_client_token.json" && \
         -s "${XDG_CACHE_HOME:-$HOME/.cache}/spotify-player/credentials.json" ]]
      ;;
    upstream-tailscale-up)
      command -v tailscale >/dev/null 2>&1 && tailscale status >/dev/null 2>&1
      ;;
    *) return 1 ;;
  esac
}

configure_micro_developer_essentials() {
  local config plugin settings bindings marker temporary backup_stamp lsp_server=""
  local -a plugins=(lsp fzf filemanager snippets autofmt detectindent jump palettero quickfix editorconfig runit)
  command -v micro >/dev/null 2>&1 || { ui_warn "Micro is not installed."; return 1; }
  command -v fzf >/dev/null 2>&1 || { ui_warn "fzf is not installed; Micro's fuzzy file opener would not work."; return 1; }
  command -v ctags >/dev/null 2>&1 || { ui_warn "ctags is not installed; Micro's symbol jump would not work."; return 1; }
  command -v jq >/dev/null 2>&1 || { ui_warn "jq is required to safely merge Micro's JSON configuration."; return 1; }
  config="${MICRO_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/micro}"
  for plugin in "${plugins[@]}"; do
    if [[ -s "$config/plug/$plugin/repo.json" ]]; then
      ui_success "Micro plugin $plugin is already installed."
    else
      run micro -plugin install "$plugin" || return 1
    fi
  done

  settings="$config/settings.json"
  bindings="$config/bindings.json"
  marker="$config/.linux-bootstrap-developer-essentials-v1"
  if [[ "$DRY_RUN" == true ]]; then
    ui_success "Micro plugins would be installed and safe defaults merged into settings.json and bindings.json."
    return 0
  fi
  run mkdir -p "$config"

  command -v clangd >/dev/null 2>&1 && lsp_server="c=clangd,c++=clangd"
  command -v gopls >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}go=gopls"
  command -v pylsp >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}python=pylsp"
  command -v rust-analyzer >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}rust=rust-analyzer"
  command -v typescript-language-server >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}javascript=typescript-language-server --stdio,typescript=typescript-language-server --stdio"
  command -v bash-language-server >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}shell=bash-language-server start"
  command -v yaml-language-server >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}yaml=yaml-language-server --stdio"
  command -v lua-language-server >/dev/null 2>&1 && lsp_server="${lsp_server:+$lsp_server,}lua=lua-language-server"

  [[ -s "$settings" ]] || printf '{}\n' > "$settings"
  jq -e 'type == "object"' "$settings" >/dev/null || { ui_warn "Micro settings.json is not a JSON object; no settings were changed."; return 1; }
  temporary="${TMPDIR:-/tmp}/linux-bootstrap-micro-settings.partial.$$"
  register_temp_artifact "$temporary"
  jq --arg server "$lsp_server" '({"lsp.formatOnSave": true, "lsp.tabcompletion": true, "parsecursor": true} + if $server != "" then {"lsp.server": $server} else {} end) as $defaults | $defaults * .' "$settings" > "$temporary"
  if ! cmp -s "$settings" "$temporary"; then
    backup_stamp="$(date +%Y%m%d-%H%M%S)"
    run cp -a "$settings" "$settings.bootstrap-backup-$backup_stamp"
    run mv "$temporary" "$settings"
  else
    rm -f "$temporary"
  fi
  unregister_temp_artifact "$temporary"

  [[ -s "$bindings" ]] || printf '{}\n' > "$bindings"
  jq -e 'type == "object"' "$bindings" >/dev/null || { ui_warn "Micro bindings.json is not a JSON object; no bindings were changed."; return 1; }
  temporary="${TMPDIR:-/tmp}/linux-bootstrap-micro-bindings.partial.$$"
  register_temp_artifact "$temporary"
  jq --argjson defaults '{"CtrlP":"command:palettero","CtrlSpace":"command:lspcompletion","F2":"command:tree","F3":"command:fzf","F4":"command:jumptag","Alt-s":"lua:snippets.Insert","Alt-n":"lua:snippets.Next","Alt-a":"lua:snippets.Accept","Alt-c":"lua:snippets.Cancel"}' '$defaults * .' "$bindings" > "$temporary"
  if ! cmp -s "$bindings" "$temporary"; then
    backup_stamp="$(date +%Y%m%d-%H%M%S)"
    run cp -a "$bindings" "$bindings.bootstrap-backup-$backup_stamp"
    run mv "$temporary" "$bindings"
  else
    rm -f "$temporary"
  fi
  unregister_temp_artifact "$temporary"
  printf 'Micro developer essentials v1\n' > "$marker"
  ui_success "Micro's full developer bundle is ready; existing choices took precedence and changed JSON files were backed up."
}

confirm_sensitive_configuration() {
  local prompt="$1" saved_assume_yes="${ASSUME_YES:-false}"
  if [[ "$DRY_RUN" == true ]]; then
    ui_warn "Dry run: a second confirmation would be required: $prompt"
    return 0
  fi
  if [[ ! -t 0 ]]; then
    ui_warn "Skipped: this account change requires an interactive confirmation."
    return 10
  fi
  ASSUME_YES=false
  if ui_confirm "$prompt" "no"; then
    ASSUME_YES="$saved_assume_yes"
    return 0
  fi
  ASSUME_YES="$saved_assume_yes"
  return 10
}

configure_fish_login_shell() {
  local fish_path current_shell account_name="${USER:-$(id -un)}"
  fish_path="$(command -v fish 2>/dev/null || true)"
  [[ -n "$fish_path" ]] || { ui_warn "Fish is not installed; login shell was not changed."; return 1; }
  current_shell="$(getent passwd "$account_name" 2>/dev/null | awk -F: '{print $7}')"
  if [[ "${current_shell:-${SHELL:-}}" == "$fish_path" ]]; then
    ui_success "Fish is already the login shell."
    return 0
  fi
  confirm_sensitive_configuration "Change the login shell for $account_name from ${current_shell:-unknown} to $fish_path?" || return $?
  if ! grep -Fxq "$fish_path" /etc/shells 2>/dev/null; then
    as_root sh -c 'grep -Fxq "$1" /etc/shells || printf "%s\n" "$1" >> /etc/shells' sh "$fish_path"
  fi
  run chsh -s "$fish_path" "$account_name"
  ui_success "Fish will become the login shell at the next login."
}

configure_fish_starship() {
  local config_dir config
  command -v fish >/dev/null 2>&1 || { ui_warn "Fish is not installed."; return 1; }
  command -v starship >/dev/null 2>&1 || { ui_warn "Starship is not installed."; return 1; }
  config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fish"
  config="$config_dir/config.fish"
  grep -Fq '# >>> linux-bootstrap starship >>>' "$config" 2>/dev/null && {
    ui_success "Starship initialization is already managed in config.fish."
    return 0
  }
  run mkdir -p "$config_dir"
  run sh -c 'printf "\n# >>> linux-bootstrap starship >>>\nif status is-interactive\n    starship init fish | source\nend\n# <<< linux-bootstrap starship <<<\n" >> "$1"' sh "$config"
}

configure_starship_preset() {
  local preset="$1" config_dir config temporary backup_stamp
  command -v starship >/dev/null 2>&1 || { ui_warn "Starship is not installed."; return 1; }
  config_dir="${XDG_CONFIG_HOME:-$HOME/.config}"
  config="$config_dir/starship.toml"
  configuration_is_complete "starship-preset-$preset" && {
    ui_success "The managed $preset preset is already configured."
    return 0
  }
  run mkdir -p "$config_dir"
  if [[ -e "$config" ]]; then
    backup_stamp="$(date +%Y%m%d-%H%M%S)"
    run cp -a "$config" "$config.bootstrap-backup-$backup_stamp"
    if [[ "$DRY_RUN" == true ]]; then ui_success "Existing Starship configuration would be backed up before replacement."
    else ui_success "Existing Starship configuration backed up before replacement."
    fi
  fi
  temporary="${TMPDIR:-/tmp}/linux-bootstrap-starship.partial.$$"
  register_temp_artifact "$temporary"
  run sh -c 'starship preset "$1" > "$2"' sh "$preset" "$temporary"
  run sed -i "1i# Generated by linux-bootstrap: $preset" "$temporary"
  run mv "$temporary" "$config"
  unregister_temp_artifact "$temporary"
}

begin_upstream_configuration() {
  local label="$1"
  if [[ "$DRY_RUN" == true ]]; then return 0; fi
  if [[ ! -t 0 || ! -t 1 ]]; then
    ui_warn "Skipped $label because its upstream setup requires an interactive terminal."
    return 10
  fi
  printf '\n=== Upstream setup: %s ===\n' "$label"
  printf 'Linux Bootstrap will resume when this program exits.\n\n'
}

configure_github_auth() {
  command -v gh >/dev/null 2>&1 || { ui_warn "GitHub CLI is not installed."; return 1; }
  configuration_is_complete upstream-github-auth && { ui_success "GitHub CLI is already authenticated."; return 0; }
  begin_upstream_configuration "GitHub CLI authentication" || return $?
  run_interactive gh auth login --hostname github.com
}

configure_spotify_auth() {
  command -v spotify_player >/dev/null 2>&1 || { ui_warn "Spotify Player is not installed."; return 1; }
  configuration_is_complete upstream-spotify-auth && { ui_success "Spotify Player credentials are already cached."; return 0; }
  begin_upstream_configuration "Spotify Player authentication" || return $?
  if [[ -n "${SSH_CONNECTION:-}" || -n "${SSH_TTY:-}" ]]; then
    ui_warn "Spotify OAuth uses 127.0.0.1:8989 on this machine. Over SSH, reconnect with local port forwarding if the callback cannot reach it: ssh -L 8989:127.0.0.1:8989 HOST"
  fi
  run_interactive spotify_player authenticate
}

configure_tailscale_up() {
  command -v tailscale >/dev/null 2>&1 || { ui_warn "Tailscale is not installed."; return 1; }
  configuration_is_complete upstream-tailscale-up && { ui_success "Tailscale is already connected."; return 0; }
  begin_upstream_configuration "Tailscale connection" || return $?
  confirm_sensitive_configuration "Run 'tailscale up' and allow Tailscale to apply its network settings?" || return $?
  run_interactive_as_root tailscale up
}

apply_configuration() {
  case "$1" in
    fish-login-shell) configure_fish_login_shell ;;
    fish-starship) configure_fish_starship ;;
    micro-developer-essentials) configure_micro_developer_essentials ;;
    starship-preset-*) configure_starship_preset "${1#starship-preset-}" ;;
    upstream-github-auth) configure_github_auth ;;
    upstream-spotify-auth) configure_spotify_auth ;;
    upstream-tailscale-up) configure_tailscale_up ;;
    *) die "Unknown configuration task '$1'." ;;
  esac
}
